name: AI Review

on:
  workflow_dispatch:
    inputs:
      review-command:
        type: choice
        default: run
        options: [ run, run-inline, run-context, run-summary, run-inline-reply, run-summary-reply ]
      pull-request-number:
        type: string
        required: true
jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: HomeBake/ai-review@v1.0.0
        with:
          review-command: ${{ inputs.review-command }}
        env:
          # --- LLM configuration ---
          LLM__PROVIDER: "OLLAMA"
          LLM__META__MODEL: "qwen3-coder:30b"
          LLM__META__TEMPERATURE: "0.1"
          LLM__HTTP_CLIENT__API_URL: "https://aurore-monogenic-nonarticulately.ngrok-free.dev"

          # --- GitHub integration ---
          VCS__PROVIDER: "GITHUB"
          VCS__PIPELINE__OWNER: ${{ github.repository_owner }}
          VCS__PIPELINE__REPO: ${{ github.event.repository.name }}
          VCS__PIPELINE__PULL_NUMBER: ${{ inputs.pull-request-number }}
          VCS__HTTP_CLIENT__API_URL: "https://api.github.com"
          VCS__HTTP_CLIENT__API_TOKEN: ${{ secrets.T_GITHUB_TOKEN }}

          # --- Prompt configuration ---
          PROMPT__INLINE_PROMPT_FILES: '["./ai-review/prompt/inline/strict.md"]'
          PROMPT__CONTEXT_PROMPT_FILES: '["./ai-review/prompt/inline/strict.md"]'
          PROMPT__SUMMARY_PROMPT_FILES: '["./ai-review/prompt/summary/strict.md"]'
          PROMPT__INLINE_REPLY_PROMPT_FILES: '["./ai-review/prompt/inline_reply/strict.md"]'
          PROMPT__SUMMARY_REPLY_PROMPT_FILES: '["./ai-review/prompt/summary_reply/strict.md"]'
          REVIEW__MODE: "FULL_FILE_CURRENT"

          LOGGER__LEVEL: "DEBUG"
          # REVIEW__DRY_RUN: true
          REVIEW__MAX_INLINE_COMMENTS: 10
          REVIEW__MAX_CONTEXT_COMMENTS: 10
          ARTIFACTS__LLM_ENABLED: true
      - name: Upload AI Review artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ai-review-artifacts
          path: ./artifacts
          retention-days: 7
